language: rust

branches:
  only:
    - master

before_install:
  - nvm install --lts
  - nvm use --lts
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - rustup component add clippy
  - rustup component add rustfmt

cache:
  - cargo
  - yarn

script:
  - yarn --frozen-lockfile
  - yarn lint
  - cargo fmt -- --check
  - cargo check
  - cargo clippy --all-targets --all-features -- -D warnings
  - yarn test
  - yarn build

before_deploy:
  - yarn global add netlify-cli

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./dist
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_success: always
