language: rust

before_install:
  - nvm install lts
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  - yarn
  - directories:
      - $HOME/.cargo

before_cache:
  - rm -rf $HOME/.cargo/registry

script:
  - yarn --frozen-lockfile
  - yarn lint
  - yarn test
  - yarn build

before_deploy:
  - yarn global add netlify-cli

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./dist
  skip_cleanup: true
  on:
    branch: master
